config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new,:create,:show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'bands#index'
end

app/models/album.rb
class Album < ApplicationRecord

  belongs_to :band

  validates :band, :title, :year, presence: true
  validates :title, uniqueness: {scope: :band_id}

  after_initialize :set_defaults

  def set_defaults
    self.live ||= false
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password
  
  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new(album_params)
  end

  def created
  end

  def edit
  end

  private
  def album_params
    params.require(:album).permit(:title, :year, :band_id, :live)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def login!(user)
    #need to set session_token in browser here
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    redirect_to users_new_url unless logged_in?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def create
    @band = Band.create!(band_params)
    redirect_to bands_url
  end

  def new
    @band = Band.new
  end

  def edit
    @band = Band.find(params[:id])
  end

  def show
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    @band.update!(band_params)
    redirect_to bands_url
  end

  def destroy
    @band = Band.find(params[:id])
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new #go to login page
    @user = User.new
  end

  def create #create a long-in session token and match to browser
      #find by user credentials validates correct login-pw combo
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user) #show page for user
    else
      redirect_to new_session_url #back to login page
    end
  end

  def destroy #delete a session_token
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = [@user.errors.full_messages]
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :session_token, :id)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'/>".html_safe
  end
#these Should be buttons or links?
  def log_in
  "<a href='#{new_session_url}'> sign in* </a>".html_safe
  end

  def sign_up #redirect_to new user form
  "<a href='#{new_user_url}'> sign up* </a>".html_safe
  end

  
end

app/helpers/bands_helper.rb
module BandsHelper
  def edit_band_link(band)
  "<a href='#{edit_band_url(band)}'>edit band</a>".html_safe
  end

  def new_band_link
    "<a href='#{new_band_url}'>add new band</a>".html_safe
  end

  def band_index_link
    "<a href='#{bands_url}'>band index</a>".html_safe
  end

  def show_band_link(band)
    "<a href='#{band_url(band)}'>show band page</a>".html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<form action="<%=albums_url%>" method="post">
  <%= auth_token %>
  <select name="band">
    <% Bands.all.each do |band| %>
    <option value=" <%= band.name %>"><%=band.name%></option>
    <% end %>
  </select>
  live<input type="radio" name="Recorded" value="live">
  studio<input type="radio" name="Recorded" value="studio" checked="true">
  <input type="submit" class="button" value="Add Album">
</form>

app/views/bands/_form.html.erb
<% if type == :new
    action_url = bands_url
    value = "add band"
    else
      action_url = band_url
      value = "update band"
    end
%>

<form action="<%=action_url%>" method="post">
  <%= auth_token %>
  <% if type == :edit %>
  <input type="hidden" name="_method" value="patch">
  <% end %>
    <label for="name">Band Name
    <input type="name" name="band[name]" value="  <%=band.name%>">
    </label>
    <input type="submit" class="button" name="" value="<%=value%>">
</form>

app/views/bands/create.html.erb
<h1>Bands#create</h1>
<p>Find me in app/views/bands/create.html.erb</p>

app/views/bands/destroy.html.erb
<h1>Bands#destroy</h1>
<p>Find me in app/views/bands/destroy.html.erb</p>

app/views/bands/edit.html.erb
<h1>Edit <%=@band.name%> name</h1>
<%= render 'form', band: @band, type: :edit %>
<%= new_band_link %>
<%= band_index_link %>

app/views/bands/index.html.erb
<h1>List of Bands</h1>
<% @bands.each do |band| %>
<ul>
  <h2> <%= band.name %> </h2>
    <li> <%= show_band_link(band) %> </li>
    <li> <%= edit_band_link(band) %> </li>
</ul>
  <% end %>

app/views/bands/new.html.erb
<h1>New Band</h1>
<%= render 'form', band: @band, type: :new %>
<%= band_index_link %>

app/views/bands/show.html.erb
<h1>Bands</h1>
  <h2> <%= @band.name %> </h2>

  <%= edit_band_link(@band) %>
  <%= new_band_link %>
  <%= band_index_link %>

app/views/bands/update.html.erb
<h1>Bands#update</h1>
<p>Find me in app/views/bands/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <header>
      <h1>MusicApp</h1>
        <% if logged_in? %>

        <h1>Welcome, <%=current_user.email%>!</h1>

          <form action="<%=session_url%>" method="post">
            <%= auth_token%>
            <input type="hidden" name="_method" value="delete">
            <input type="submit" class="button" name="" value="Log Out">
          </form>
        <% else %>
        <nav>
          <%= sign_up %>
          <%= log_in  %>
        </nav>
        <% end %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% type == :sign_in ? action_url = session_url : action_url = users_url %>

<form action="<%=action_url%>" method="post">
  <%= auth_token %>
    <label for="email">Email
    <input type="email" name="user[email]" value="">
    </label>
    <label for="password">Password
    <input type="password" name="user[password]" value="">
    </label>
    <input type="submit" class="button" name="" value="Let's go!">
</form>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>New User Sign Up Page</h1>
  <%= render 'form', user: @user, type: :new %>

app/views/users/show.html.erb
<h1> <%= @user.email %>'s page </h1>